<?php

/**
 * PluginProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginProductTable
     */
    public static function getInstance()
    {
      return Doctrine_Core::getTable('PluginProduct');
    }
    
    public static function getProductsWithCategories()
    {
      $q = Doctrine_Query::create()->from('Product p')->leftJoin('p.Categories c')->orderby('c.name');
      return $q->execute();
    }
    
      
  
  	public static function getProductsWithCategoriesFiltered($catid)
    {
        $node = Doctrine_Core::getTable('Category')->findOneById($catid)->getNode();
        $cats[0] = $node->getRecord()->getId();
        /*if ($node->hasChildren()) {
          $i = 1;
          $descendants = $node->getDescendants();
          foreach ($descendants as $descendant) {
            $cats[$i] = $descendant['id'];
            $i++;
          }
        }*/
        
        $q = Doctrine_Query::create()->from('Product p')->innerJoin('p.Categories c')->andWhereIn('c.id', $cats);

        return $q->execute();
      

    }

    
}