<?php

/**
 * PluginCategoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCategoryTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object PluginCategoryTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('PluginCategory');
	}


	public static function getCategoriesWithProducts()
	{
		$q = Doctrine_Query::create()->from('Category c')->leftJoin('c.Products p')->where('c.active=1')->orderBy('c.root_id, c.level desc');
		return $q->execute();
	}
}