<?php

/**
 * PluginProductCategoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductCategoryTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object PluginProductCategoryTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('PluginProductCategory');
	}
}