<?php

/**
 * PluginCouponTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCouponTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCouponTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCoupon');
    }
}