<?php

/**
 * PluginProductTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginProductTable extends Doctrine_Table
{
	/**
	 * Returns an instance of this class.
	 *
	 * @return object PluginProductTable
	 */
	public static function getInstance()
	{
		return Doctrine_Core::getTable('PluginProduct');
	}

	//Return a table of all products joined to categories, ordered by category name.
	public static function getProductsWithCategories()
	{
		$q = Doctrine_Query::create()->from('Product p')->leftJoin('p.Categories c')->orderby('c.name');
		return $q->execute();
	}

	//Gets products that are part of a specified category ID
	public static function getProductsWithCategoriesFiltered($catid)
	{
		$node = Doctrine_Core::getTable('Category')->findOneById($catid)->getNode();
		$cats[0] = $node->getRecord()->getId();

		$q = Doctrine_Query::create()->from('Product p')->innerJoin('p.Categories c')->andWhereIn('c.id', $cats);

		return $q->execute();


	}


}