<?php

/**
 * PluginSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSettings');
    }
}